// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHLTYqyq99EzXitFUEwC82mjgdD0Cbkpk',
    appId: '1:419779331224:web:70970a5afa578b4d0dbced',
    messagingSenderId: '419779331224',
    projectId: 'autoguardflutter',
    authDomain: 'autoguardflutter.firebaseapp.com',
    storageBucket: 'autoguardflutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIk8hjkpjTVzBNrPOgWe-4C2n-cdJiFvk',
    appId: '1:419779331224:android:504cca73703a07c60dbced',
    messagingSenderId: '419779331224',
    projectId: 'autoguardflutter',
    storageBucket: 'autoguardflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUSTEo9DoRaJtk0AWIhJgN2e2bBMNv1_Q',
    appId: '1:419779331224:ios:c81196b6a306ef360dbced',
    messagingSenderId: '419779331224',
    projectId: 'autoguardflutter',
    storageBucket: 'autoguardflutter.firebasestorage.app',
    iosBundleId: 'com.example.autoguardFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUSTEo9DoRaJtk0AWIhJgN2e2bBMNv1_Q',
    appId: '1:419779331224:ios:c81196b6a306ef360dbced',
    messagingSenderId: '419779331224',
    projectId: 'autoguardflutter',
    storageBucket: 'autoguardflutter.firebasestorage.app',
    iosBundleId: 'com.example.autoguardFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHLTYqyq99EzXitFUEwC82mjgdD0Cbkpk',
    appId: '1:419779331224:web:3157e98d15d06e950dbced',
    messagingSenderId: '419779331224',
    projectId: 'autoguardflutter',
    authDomain: 'autoguardflutter.firebaseapp.com',
    storageBucket: 'autoguardflutter.firebasestorage.app',
  );
}
